snekbox_url = "http://snekbox:8060/eval"

[bot]
prefix = "!"
token_file = "env/token.txt"

[guild]
teachers = [182894631921516545, 686394452788773036]
question_channel = 1013601747966644365
student_channels = [
    1014373177360662640,
    1014373098184777728,
    1014373012105089134,
]


[guild.roles]
students = 1013602964188975165

